### ISSUE TITLE
IntelliJ freezes on changing gradle dependencies in 2018.2.x

### ISSUE THREAD

**Issue by immondu** [dubreuia/intellij-plugin-save-actions#184]
**What happens?**
I edit an Gradle file, changing the dependencies. Just Typing one character in the dependencies String. (With this single character the dependency is not valid.) After that, IntelliJ freezes. Everything is visible as bevor, but by moving the mouse there are no mouse over effects, nothing is clickable, IntelliJ can only be terminated from outside. When restarting the changes seem to have been persisted. I can use the IDE again. I can delete the added caracter and it does not Freeze. But when I add another character again, it freezes again. It doesn't recover within 10 Minutes, so I terminated it again. CPU-Usage increases to 120% to 150%.

**Reproducable?**
It happens on my computer but also on those of colleagues in different projects. But just in some Projects. In those Projects it always happens. I could not reproduce it with an new empty Project so far. 

**Versions**
It happens with IntelliJ 2018.2.0, 2018.2.1 and 2018.2.2
It does not happen with IntelliJ 2018.1.6

**Setting**
Save Actions 1.0.0

IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.33, built on August 21, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by dubreuia** [comment]
Hey @immondu. Did you template your own issue format? That's really good bug redaction. Thanks a lot. And thank you for testing in multiple versions of Intellij.

Can you please post the content of two files (those from https://github.com/dubreuia/intellij-plugin-save-actions#files-location): `~/.IntelliJIdeaVERSION/system/log/idea.log` (you can grep SaveActionManager if you don't want to send everything) and `.idea/saveactions_settings.xml`.

Two follow up questions:

- Why do you think this is specific to save-actions? What happens if you deactivate the plugin (in "Other Settings > Save Actions > Activate save actions"?
- Does it only happen while editing gradle files? Or any files?

A possible workaround for now: 

- Go to "Other Settings > Save Actions > Exclusions"
- Choose "Add exclusion" then add `build.gradle` or `*.gradle`

**Comment by bkushigian** [comment]
I can second this, started experiencing this when I updated Intellij versions.

**Comment by dubreuia** [comment]
A possible workaround for now: 

- Go to "Other Settings > Save Actions > Exclusions"
- Choose "Add exclusion" then add `build.gradle` or `*.gradle`

**Comment by vrobertson** [comment]
Is is probably not "Save Action" plugin bug.
There was a bug in Groovy plugin in IDEA 2018.2, 2018.2.1, 2018.2.2 versions. Fixed in 2018.2.3.

**Comment by immondu** [comment]
That is not the case. The Bug still appears. My IntelliJ IDEA 2018.2.3 with Save Actions 1.1.0 still freezes, if I edit an build.gradle File.

**Comment by immondu** [comment]
This Bug still appears with IntelliJ IDEA 2018.2.4 with Save Actions 1.2.0.

**Comment by dubreuia** [comment]
I've just tested it and I can't reproduce. It is working a bit too well since it is reformatting the file as I type, but no freeze.

I'm pretty sure it is a conflict between save-actions and another plugin that binds to the document saving event (probably infinite loop). Can you post what plugins you have installed? Like gradle plugin, eclipse formater plugin, etc.

**Comment by immondu** [comment]
I'll only write the custom Plugins, hope that that's enough:

- BashSupport
- ESLint
- IDETalk
- LiveEdit
- Lombock Plugin
- NodeJS
- Properties to YAML Converter
- Save Actions
- SonarLint
- Vue.js

I'll try it without other plugins later.

**Comment by immondu** [comment]
Wenn ich alle custom Plugins außer Save Actions deaktiviere habe ich trotzdem noch das gleiche Phänomen. =(

**Comment by immondu** [comment]
Oh, after a couple of minutes the IntelliJ-Window closed and I've got back to the project selection and could see the following error message there:
Exception in plugin *Save Actions*. Moments ago. Occurred once since the last clear. [Disable plugin ...](#)
This plugin is not a production of JetBrains. Please report the problem to [Alexandre DuBreuil](https://github.com/dubreuia). 
```
java.lang.AssertionError: Already disposed: Project (Disposed) my-project-name
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:248)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:955)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:246)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:239)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:45)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:42)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:30)
	at com.intellij.openapi.vfs.ReadonlyStatusHandler.getInstance(ReadonlyStatusHandler.java:68)
	at com.intellij.codeInsight.CodeInsightUtilBase.preparePsiElementsForWrite(CodeInsightUtilBase.java:89)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:257)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:244)
	at com.dubreuia.processors.java.InspectionProcessor.lambda$run$0(InspectionProcessor.java:49)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by dubreuia** [comment]
Thanks for the stack @immondu. I'm already checking if the project is disposed before executing the actions, this seems like a race condition between the time I check and the time the inspection is actually triggered. I'll try to reproduce.

As for your plugin list, I'm pretty sure "Lombok plugin" doesn't work well with Save Actions, I've had problems before since they both bind to the same event.

> But if I'm deactivating all custom plugins except save actions I've still the same issue. =(

:(

**Comment by immondu** [comment]
I usually have the Lombok plugin deactivated. Just had a single project where I've used it and forgot to turn it off again. Ask if I can check something else, that is a useful information to solve this bug.

**Comment by dubreuia** [comment]
WNF
