### ISSUE TITLE
Nothing happens in IntelliJ 14 Ultimate

### ISSUE THREAD

**Issue by yrn1** [dubreuia/intellij-plugin-save-actions#4]
I installed the plugin, restarted IntelliJ, enabled Save actions in its config pane, but it does not seem to do anything. I tried
* restarting IntelliJ: no difference
* different ways of saving: ctrl-s, triggering a build, quitting IntelliJ: no actions
* looking in idea.log: Save Action plugin is enabled, but no further output from the plugin.

Any idea?

btw. this plugin is a great idea ;-)

**Comment by dubreuia** [comment]
Make sure you have activated at least one action (for example the "organize imports" action) in "File > Settings > Other Settings > Save actions". Make sure those are checked:

- "Activate save actions"
- "Organize imports"

Then go in a file (Java ?) and type an unused import "import java.util.Map. Then either (I) change window OR (II) save-all with CTRL-S. You should instantly see the import go away.

If that doesn't work, send me your exact Intellij and plugin version.

**Comment by dubreuia** [comment]
Oh and the plugin is dependent on your "organize import" and "reformat code" configuration, which are visible from "File > Settings > Editor > General > Formatting". Tick the boxes, then organize imports or reformat code which will show the dialog boxes, and check your config.

**Comment by yrn1** [comment]
Did exactly that, but it still does nothing. These are my versions:
- IntelliJ Ultimate 14.0.2 build #IU-139.659
- JRE 1.7.0_71-b14
- Save Actions Version 0.2

**Comment by dubreuia** [comment]
CTRL-ALT-L ? What OS are you using ?

**Comment by yrn1** [comment]
Windows 7

**Comment by dubreuia** [comment]
I have an idea I check it out and keep you posted.

**Comment by dubreuia** [comment]
Confirmed today on a coworker's windows machine

**Comment by dubreuia** [comment]
It seems it is corrected by #7

**Comment by yrn1** [comment]
Still does nothing on my IntelliJ Ultimate 14.1.2, on Windows 7, even with the hints from #7

**Comment by dubreuia** [comment]
Confirmed working on all machines at work (Windows / Unix / Mac) and many versions.

I'll do something: I'll add some logging in the next plugin version (0.5), and you'll send me the log file so I can debug more easily.

**Comment by scheglov** [comment]
Does not work for me on Mac 
![image](https://cloud.githubusercontent.com/assets/384794/8843761/c64acd0c-30c1-11e5-860c-4ffae020c016.png) with Java 
![image](https://cloud.githubusercontent.com/assets/384794/8843764/d80defc4-30c1-11e5-89aa-0f290423e04c.png)

**Comment by dubreuia** [comment]
I cannot reproduce @scheglov, but I'll add log info for cases like yours. Make sure you have installed the plugin through Intellij's plugin management, and that it is activated in the settings.

**Comment by crisfl** [comment]
Same problem as @scheglov, doesn't work on Mac.
I have the same exact version.
I did install the plugin through IntelliJ's plugin management and it is activated.

**Comment by LeonidVlad** [comment]
Doe not work for me on Windows 7. I tried for AndroidStudio 1.3.2 and IntelliJ 14.1.4.
Just does nothing.
If you added the logs, where can we look at them?

**Comment by mstefancic** [comment]
Not working for me on Mac either. Jus happens nothing. Same version as @scheglov, but version before didn't work too.

**Comment by dubreuia** [comment]
I'm going to add the logs asap, it's almost done. I'll keep you posted.

**Comment by pcalouche** [comment]
Any updates on this?  I'm seeing similar behavior.  I'm using Windows 7, IntelliJ 15.03, Build #IU-143.1821. I have a Windows 10 machine with the same setup, and it works.  Maybe a clue?

**Comment by pcalouche** [comment]
I compiled your 0.5 plugin that had the logging, and I think I have an idea of what may be going on.  

If the project is configured to so that project files are kept in a separate folder than the source files I see something like this:

2016-01-29 09:01:14,526 [ 386532]  DEBUG - com.dubreuia.SaveActionManager - File C:/Users/pcalouch/Repos/spat/src/main/java/com/calouche/spat/controller/HomeController.java not in project Project 'C:\Users\pcalouch\Projects\spat' spat 

If the project files are not separate then it seems to work:

2016-01-29 09:11:43,706 [1015712]  DEBUG - com.dubreuia.SaveActionManager - Running processors [optimize imports processor, null, reformat code processor - all text], file PsiJavaFile:HomeController.java, project Project 'C:\Users\pcalouch\Repos\spat' spat 

This would explain why it worked for me on the Windows 10 machine too.  I'm not keeping the project files in a separate folder in that setup.

I hope this information is helpful.

**Comment by dubreuia** [comment]
Thanks a lot @pcalouche for the debug. I thought it was the problem but couldn't confirm it. I'll correct the problem, it's a side effect of the correction for bug #1.

**Comment by dubreuia** [comment]
Corrected in 0.5

**Comment by pcalouche** [comment]
Glad I could help @dubreuia and glad it is closed.  How long does it take the IntelliJ Plugin Repository to update to the newest version?

**Comment by dubreuia** [comment]
Jetbrains validates them pretty fast, normally 1 business day. 

I did a release too and attached the binary if you want to try it before: https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v0.5

**Comment by pcalouche** [comment]
Changes look good @dubreuia .  Thanks for the update.  I think I noticed a typo in the options screen after the change.  I think Organize organize used to be Organize imports.

**Comment by dubreuia** [comment]
The plugin is out. Thanks for the heads up about the typo.
